nameOverride: ""
fullnameOverride: ""

app:
  replicaCount: 1
  image:
    repository: trial29e6cp.jfrog.io/docker-trial/devops-tech-challenge-app
    tag: "docker-22bf120a"
    pullPolicy: IfNotPresent
  imagePullSecrets:
    - jfrog-regcred
  containerPort: 3000
  env:
    NODE_ENV: "development"
    MONGO_DB: "visitsdb_dev"
    # default uri; për dev/test do e override me values files
    MONGODB_URI: "mongodb://root:rootpass@mongo:27017/visitsdb_dev?authSource=admin"

service:
  name: service-devops-tech-challenge
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: nginx
  host: ""   # bosh => vetëm rule pa host (si tek YAML yt)
  path: /
  pathType: Prefix

mongo:
  enabled: true
  image: "mongo:7"
  port: 27017
  auth:
    username: "root"
    password: "rootpass"
  database: "visitsdb_dev"
