apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-tech-challenge
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-tech-challenge
  template:
    metadata:
      labels:
        app: devops-tech-challenge
    spec:
      imagePullSecrets:
        - name: jfrog-regcred
      containers:
        - name: app
          image: trial29e6cp.jfrog.io/docker-trial/devops-tech-challenge-app:docker-0a4eeba1
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: MONGO_DB
              value: "visitsdb_dev"
            - name: MONGODB_URI
              value: "mongodb://root:rootpass@mongo:27017/visitsdb_dev?authSource=admin"

          startupProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 2
            timeoutSeconds: 2
            failureThreshold: 45

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 12

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 6
