apiVersion: v1
kind: Service
metadata:
  name: service-devops-tech-challenge
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: devops-tech-challenge
  ports:
    - port: 80
      targetPort: 3000
