apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: visits-ingress
  namespace: visits
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: visits.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: visits-app
                port:
                  number: 3000
